filebeat.modules:
- module: auditd
- module: nginx
- module: system


name: "{{ inventory_hostname }}"
tags: ["{{ env }}"]


processors:
- add_cloud_metadata: ~
- add_host_metadata: ~


xpack.monitoring.enabled: true


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "${ES_PWD}"

#cloud.id: ""
#cloud.auth: "elastic:YOUR_PASSWORD"
