heartbeat.monitors:

{% if domain is defined and domain %}
- type: http
  name: Webserver
  urls: ["https://{{ domain }}"]
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200

- type: http
  name: Kibana
  urls: ["https://kibana.{{ domain }}"]
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200
{% else %}
- type: http
  name: Webserver
  urls: ["http://localhost"]
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200
{% endif %}

- type: http
  name: Elasticsearch
  urls: ["{{ elasticsearch_host }}"]
  username: {{ elasticsearch_user }}
  password: "${ES_PWD}"
  schedule: "@every 10s"
  timeout: 3s
  check.response.status: 200


name: "{{ inventory_hostname }}"
tags: ["{{ env }}"]


processors:
- add_cloud_metadata: ~
- add_host_metadata: ~
- add_observer_metadata:
    geo:
      name: eu-central-1
      location: 50.1105, 8.6822
      continent_name: Europe
      country_iso_code: DE
      city_name: Frankfurt


monitoring.enabled: true


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "${ES_PWD}"

#cloud.id: ""
#cloud.auth: "{{ elasticsearch_user }}:${ES_PWD}"
