packetbeat.interfaces.device: any


packetbeat.flows:
  timeout: 30s
  period: 10s


packetbeat.protocols:

- type: icmp
  enabled: true

- type: dns
  ports: [53]

- type: http
  ports: [80]

- type: tls
  ports: [443]


packetbeat.procs:
  enabled: true
  monitored:

    - process: nginx
      cmdline_grep: nginx


name: "{{ inventory_hostname }}"
tags: ["{{ env }}"]


processors:

- add_cloud_metadata: ~
- add_host_metadata: ~


monitoring.enabled: true


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "${ES_PWD}"

setup.kibana:
  host: "{{ kibana_host }}"
  username: "{{ elasticsearch_user }}"
  password: "${ES_PWD}"

#cloud.id: ""
#cloud.auth: "{{ elasticsearch_user }}:${ES_PWD}"
